name = "Turtle"
grammar = "turtle"
path_suffixes = ["ttl", "turtle"]
line_comments = ["# "]
tab_size = 2
hard_tabs = false

[[brackets]]
start = "("
end = ")"
close = true
surround = true
newline = false

[[brackets]]
start = "["
end = "]"
close = true
surround = true
newline = false
