name = "Turtle"
grammar = "turtle"
path_suffixes = ["ttl", "turtle"]
line_comments = ["# "]
tab_size = 2
hard_tabs = false

[[brackets]]
start = "("
end = ")"
close_before = ""
newline_between = false

[[brackets]]
start = "["
end = "]"
close_before = ""
newline_between = false
