//! PROV-O (Provenance Ontology) vocabulary terms.
//!
//! Namespace: `http://www.w3.org/ns/prov#`
//! Reference: <https://www.w3.org/TR/prov-o/>

/// PROV-O namespace IRI (trailing `#`).
pub const NS: &str = "http://www.w3.org/ns/prov#";

// ── Core classes ──────────────────────────────────────────────────────────────

/// `prov:Entity` — A physical, digital, conceptual, or other kind of thing with some fixed aspects.
///
/// Label: "Entity"
///
/// Description: "An entity is a physical, digital, conceptual, or other kind of thing with some fixed aspects; entities may be real or imaginary."
pub const ENTITY: &str = "http://www.w3.org/ns/prov#Entity";

/// `prov:Activity` — Something that occurs over a period of time and acts upon or with entities.
///
/// Label: "Activity"
///
/// Description: "An activity is something that occurs over a period of time and acts upon or with entities; it may include consuming, processing, transforming, modifying, relocating, using, or generating entities."
pub const ACTIVITY: &str = "http://www.w3.org/ns/prov#Activity";

/// `prov:Agent` — Something that bears some form of responsibility for an activity.
///
/// Label: "Agent"
///
/// Description: "An agent is something that bears some form of responsibility for an activity taking place, for the existence of an entity, or for another agent's activity."
pub const AGENT: &str = "http://www.w3.org/ns/prov#Agent";

/// `prov:Plan` — A set of actions or steps intended by one or more agents to achieve some goals.
///
/// Label: "Plan"
///
/// Description: "A plan is an entity that represents a set of actions or steps intended by one or more agents to achieve some goals."
pub const PLAN: &str = "http://www.w3.org/ns/prov#Plan";

/// `prov:Bundle` — A named set of provenance descriptions.
///
/// Label: "Bundle"
///
/// Description: "A bundle is a named set of provenance descriptions, and is itself an entity, so allowing provenance of provenance to be expressed."
pub const BUNDLE: &str = "http://www.w3.org/ns/prov#Bundle";

/// `prov:Collection` — A type of entity that contains one or more entities.
///
/// Label: "Collection"
///
/// Description: "A collection is an entity that provides a structure to some constituents, which are themselves entities. These constituents are said to be member of the collections."
pub const COLLECTION: &str = "http://www.w3.org/ns/prov#Collection";

/// `prov:EmptyCollection` — An empty collection without any members.
///
/// Label: "`EmptyCollection`"
///
/// Description: "An empty collection is a collection without members."
pub const EMPTY_COLLECTION: &str = "http://www.w3.org/ns/prov#EmptyCollection";

/// `prov:Location` — A location can be an identifiable geographic place.
///
/// Label: "Location"
///
/// Description: "A location can be an identifiable geographic place (ISO 19112), but it can also be a non-geographic place such as a directory, row, or column."
pub const LOCATION: &str = "http://www.w3.org/ns/prov#Location";

/// `prov:Organization` — An organization is a social or legal institution.
///
/// Label: "Organization"
///
/// Description: "An organization is a social or legal institution such as a company, society, etc."
pub const ORGANIZATION: &str = "http://www.w3.org/ns/prov#Organization";

/// `prov:Person` — A person is an agent who has personhood.
///
/// Label: "Person"
///
/// Description: "Person agents are people."
pub const PERSON: &str = "http://www.w3.org/ns/prov#Person";

/// `prov:SoftwareAgent` — A software agent is running software.
///
/// Label: "`SoftwareAgent`"
///
/// Description: "A software agent is running software."
pub const SOFTWARE_AGENT: &str = "http://www.w3.org/ns/prov#SoftwareAgent";

// ── Derivation / generation / usage ──────────────────────────────────────────

/// `prov:wasGeneratedBy` — An entity was generated by an activity.
///
/// Label: "wasGeneratedBy"
///
/// Description: "Generation is the completion of production of a new entity by an activity. This entity did not exist before generation and becomes available for usage after this generation."
pub const WAS_GENERATED_BY: &str = "http://www.w3.org/ns/prov#wasGeneratedBy";

/// `prov:wasDerivedFrom` — An entity was derived from another entity.
///
/// Label: "wasDerivedFrom"
///
/// Description: "A derivation is a transformation of an entity into another, an update of an entity resulting in a new one, or the construction of a new entity based on a pre-existing entity."
pub const WAS_DERIVED_FROM: &str = "http://www.w3.org/ns/prov#wasDerivedFrom";

/// `prov:wasAttributedTo` — Attribution of an entity to an agent.
///
/// Label: "wasAttributedTo"
///
/// Description: "Attribution is the ascribing of an entity to an agent."
pub const WAS_ATTRIBUTED_TO: &str = "http://www.w3.org/ns/prov#wasAttributedTo";

/// `prov:used` — An activity used an entity.
///
/// Label: "used"
///
/// Description: "Usage is the beginning of utilizing an entity by an activity. Before usage, the activity had not begun to utilize this entity and could not have been affected by the entity."
pub const USED: &str = "http://www.w3.org/ns/prov#used";

/// `prov:wasInformedBy` — An activity was informed by another activity.
///
/// Label: "wasInformedBy"
///
/// Description: "Communication is the exchange of an entity by two activities, one activity using the entity generated by the other."
pub const WAS_INFORMED_BY: &str = "http://www.w3.org/ns/prov#wasInformedBy";

/// `prov:wasAssociatedWith` — An activity was associated with an agent.
///
/// Label: "wasAssociatedWith"
///
/// Description: "An activity association is an assignment of responsibility to an agent for an activity, indicating that the agent had a role in the activity."
pub const WAS_ASSOCIATED_WITH: &str = "http://www.w3.org/ns/prov#wasAssociatedWith";

/// `prov:actedOnBehalfOf` — An agent acted on behalf of another agent.
///
/// Label: "actedOnBehalfOf"
///
/// Description: "Delegation is the assignment of authority and responsibility to an agent (by itself or by another agent) to carry out a specific activity as a delegate or representative."
pub const ACTED_ON_BEHALF_OF: &str = "http://www.w3.org/ns/prov#actedOnBehalfOf";

// ── Temporal properties ───────────────────────────────────────────────────────

/// `prov:startedAtTime` — The time at which an activity started.
///
/// Label: "startedAtTime"
///
/// Description: "Start is when an activity is deemed to have been started by an entity, known as trigger."
pub const STARTED_AT_TIME: &str = "http://www.w3.org/ns/prov#startedAtTime";

/// `prov:endedAtTime` — The time at which an activity ended.
///
/// Label: "endedAtTime"
///
/// Description: "End is when an activity is deemed to have been ended by an entity, known as trigger."
pub const ENDED_AT_TIME: &str = "http://www.w3.org/ns/prov#endedAtTime";

/// `prov:generatedAtTime` — The time at which an entity was completely created and is available for use.
///
/// Label: "generatedAtTime"
///
/// Description: "Generation is the completion of production of a new entity by an activity. This entity did not exist before generation and becomes available for usage after this generation."
pub const GENERATED_AT_TIME: &str = "http://www.w3.org/ns/prov#generatedAtTime";

/// `prov:invalidatedAtTime` — The time at which an entity was invalidated.
///
/// Label: "invalidatedAtTime"
///
/// Description: "Invalidation is the start of the destruction, cessation, or expiry of an existing entity by an activity."
pub const INVALIDATED_AT_TIME: &str = "http://www.w3.org/ns/prov#invalidatedAtTime";

// ── Qualified classes ─────────────────────────────────────────────────────────

/// `prov:Usage` — A usage is the beginning of utilizing an entity by an activity.
///
/// Label: "Usage"
///
/// Description: "Usage is the beginning of utilizing an entity by an activity."
pub const USAGE: &str = "http://www.w3.org/ns/prov#Usage";

/// `prov:Generation` — The completion of production of a new entity by an activity.
///
/// Label: "Generation"
///
/// Description: "Generation is the completion of production of a new entity by an activity."
pub const GENERATION: &str = "http://www.w3.org/ns/prov#Generation";

/// `prov:Invalidation` — The start of the destruction of an entity by an activity.
///
/// Label: "Invalidation"
///
/// Description: "Invalidation is the start of the destruction, cessation, or expiry of an existing entity by an activity."
pub const INVALIDATION: &str = "http://www.w3.org/ns/prov#Invalidation";

/// `prov:Communication` — The exchange of an entity by two activities.
///
/// Label: "Communication"
///
/// Description: "Communication is the exchange of an entity by two activities, one activity using the entity generated by the other."
pub const COMMUNICATION: &str = "http://www.w3.org/ns/prov#Communication";

/// `prov:Start` — When an activity is started by an entity.
///
/// Label: "Start"
///
/// Description: "Start is when an activity is deemed to have been started by an entity, known as trigger."
pub const START: &str = "http://www.w3.org/ns/prov#Start";

/// `prov:End` — When an activity is ended by an entity.
///
/// Label: "End"
///
/// Description: "End is when an activity is deemed to have been ended by an entity, known as trigger."
pub const END: &str = "http://www.w3.org/ns/prov#End";

/// `prov:Derivation` — A transformation of an entity into another.
///
/// Label: "Derivation"
///
/// Description: "A derivation is a transformation of an entity into another, an update of an entity resulting in a new one, or the construction of a new entity based on a pre-existing entity."
pub const DERIVATION: &str = "http://www.w3.org/ns/prov#Derivation";

/// `prov:Attribution` — The ascribing of an entity to an agent.
///
/// Label: "Attribution"
///
/// Description: "Attribution is the ascribing of an entity to an agent."
pub const ATTRIBUTION: &str = "http://www.w3.org/ns/prov#Attribution";

/// `prov:Association` — An assignment of responsibility for an activity.
///
/// Label: "Association"
///
/// Description: "An activity association is an assignment of responsibility to an agent for an activity, indicating that the agent had a role in the activity."
pub const ASSOCIATION: &str = "http://www.w3.org/ns/prov#Association";

/// `prov:Delegation` — The assignment of authority to an agent.
///
/// Label: "Delegation"
///
/// Description: "Delegation is the assignment of authority and responsibility to an agent (by itself or by another agent) to carry out a specific activity as a delegate or representative."
pub const DELEGATION: &str = "http://www.w3.org/ns/prov#Delegation";

/// `prov:Influence` — Capacity of an entity, activity, or agent to have an effect.
///
/// Label: "Influence"
///
/// Description: "Influence is the capacity of an entity, activity, or agent to have an effect on the character, development, or behavior of another."
pub const INFLUENCE: &str = "http://www.w3.org/ns/prov#Influence";

// ── Qualified properties ──────────────────────────────────────────────────────

/// `prov:qualifiedUsage` — The qualified use of an entity by an activity.
///
/// Label: "qualifiedUsage"
///
/// Description: "If this Activity prov:used Entity :e, then it can qualify how it used it using prov:qualifiedUsage [ a prov:Usage; prov:entity :e; :foo :bar ]."
pub const QUALIFIED_USAGE: &str = "http://www.w3.org/ns/prov#qualifiedUsage";

/// `prov:qualifiedGeneration` — The qualified generation of an entity by an activity.
///
/// Label: "qualifiedGeneration"
///
/// Description: "If this Activity prov:generated Entity :e, then it can qualify how it generated it using prov:qualifiedGeneration [ a prov:Generation; prov:entity :e; :foo :bar ]."
pub const QUALIFIED_GENERATION: &str = "http://www.w3.org/ns/prov#qualifiedGeneration";

/// `prov:qualifiedDerivation` — A qualified derivation of this entity from another entity.
///
/// Label: "qualifiedDerivation"
///
/// Description: "If this Entity prov:wasDerivedFrom Entity :e, then it can qualify how using prov:qualifiedDerivation [ a prov:Derivation; prov:entity :e; :foo :bar ]."
pub const QUALIFIED_DERIVATION: &str = "http://www.w3.org/ns/prov#qualifiedDerivation";

/// `prov:qualifiedAttribution` — A qualified attribution of this entity to an agent.
///
/// Label: "qualifiedAttribution"
///
/// Description: "If this Entity prov:wasAttributedTo Agent :ag, then it can qualify how it was attributed using prov:qualifiedAttribution [ a prov:Attribution; prov:agent :ag; :foo :bar ]."
pub const QUALIFIED_ATTRIBUTION: &str =
    "http://www.w3.org/ns/prov#qualifiedAttribution";

/// `prov:qualifiedAssociation` — A qualified association of an activity with an agent.
///
/// Label: "qualifiedAssociation"
///
/// Description: "If this Activity prov:wasAssociatedWith Agent :ag, then it can qualify how using prov:qualifiedAssociation [ a prov:Association; prov:agent :ag; :foo :bar ]."
pub const QUALIFIED_ASSOCIATION: &str =
    "http://www.w3.org/ns/prov#qualifiedAssociation";

/// `prov:qualifiedCommunication` — A qualified communication from one activity to another.
///
/// Label: "qualifiedCommunication"
///
/// Description: "If this Activity prov:wasInformedBy Activity :a, then it can qualify how using prov:qualifiedCommunication [ a prov:Communication; prov:activity :a; :foo :bar ]."
pub const QUALIFIED_COMMUNICATION: &str =
    "http://www.w3.org/ns/prov#qualifiedCommunication";

/// `prov:qualifiedDelegation` — A qualified delegation of authority to an agent.
///
/// Label: "qualifiedDelegation"
///
/// Description: "If this Agent prov:actedOnBehalfOf Agent :ag, then it can qualify how using prov:qualifiedDelegation [ a prov:Delegation; prov:agent :ag; :foo :bar ]."
pub const QUALIFIED_DELEGATION: &str = "http://www.w3.org/ns/prov#qualifiedDelegation";

/// `prov:qualifiedStart` — A qualified start of an activity.
///
/// Label: "qualifiedStart"
///
/// Description: "If this Activity prov:wasStartedBy Entity :e1, then it can qualify how it was started using prov:qualifiedStart [ a prov:Start; prov:entity :e1; :foo :bar ]."
pub const QUALIFIED_START: &str = "http://www.w3.org/ns/prov#qualifiedStart";

/// `prov:qualifiedEnd` — A qualified end of an activity.
///
/// Label: "qualifiedEnd"
///
/// Description: "If this Activity prov:wasEndedBy Entity :e1, then it can qualify how it was ended using prov:qualifiedEnd [ a prov:End; prov:entity :e1; :foo :bar ]."
pub const QUALIFIED_END: &str = "http://www.w3.org/ns/prov#qualifiedEnd";

/// `prov:qualifiedInfluence` — A qualified influence of one resource on another.
///
/// Label: "qualifiedInfluence"
///
/// Description: "Because prov:influenced is a broad relation, its most specific subproperties (e.g. prov:wasGeneratedBy, prov:used, prov:wasAttributedTo, prov:wasAssociatedWith, prov:actedOnBehalfOf) should be used when applicable. prov:qualifiedInfluence allows representing this more generally."
pub const QUALIFIED_INFLUENCE: &str = "http://www.w3.org/ns/prov#qualifiedInfluence";

// ── Miscellaneous properties ──────────────────────────────────────────────────

/// `prov:entity` — An entity used, generated, or attributed to by a qualified influence.
///
/// Label: "entity"
///
/// Description: "The prov:entity property references an prov:Entity which influenced a resource."
pub const ENTITY_PROP: &str = "http://www.w3.org/ns/prov#entity";

/// `prov:activity` — An activity associated with a qualified influence.
///
/// Label: "activity"
///
/// Description: "The prov:activity property references an prov:Activity which influenced a resource."
pub const ACTIVITY_PROP: &str = "http://www.w3.org/ns/prov#activity";

/// `prov:agent` — An agent associated with a qualified influence.
///
/// Label: "agent"
///
/// Description: "The prov:agent property references an prov:Agent which influenced a resource."
pub const AGENT_PROP: &str = "http://www.w3.org/ns/prov#agent";

/// `prov:hadPlan` — The plan adopted by an agent in an association.
///
/// Label: "hadPlan"
///
/// Description: "The prov:hadPlan property references an prov:Plan used by an prov:Agent during an prov:Association."
pub const HAD_PLAN: &str = "http://www.w3.org/ns/prov#hadPlan";

/// `prov:hadRole` — A role played by an entity in the context of an influence.
///
/// Label: "hadRole"
///
/// Description: "The prov:hadRole property references an prov:Role played by an prov:Entity or prov:Agent."
pub const HAD_ROLE: &str = "http://www.w3.org/ns/prov#hadRole";

/// `prov:atLocation` — A location for any resource.
///
/// Label: "atLocation"
///
/// Description: "The Location of any resource."
pub const AT_LOCATION: &str = "http://www.w3.org/ns/prov#atLocation";

/// `prov:atTime` — The time at which an instantaneous event occurred.
///
/// Label: "atTime"
///
/// Description: "The prov:atTime property expresses when an instantaneous event occurred."
pub const AT_TIME: &str = "http://www.w3.org/ns/prov#atTime";

/// `prov:hadMember` — A member of the given collection.
///
/// Label: "hadMember"
///
/// Description: "The prov:hadMember property references an prov:Entity that is or was a member of a prov:Collection."
pub const HAD_MEMBER: &str = "http://www.w3.org/ns/prov#hadMember";

/// `prov:influenced` — Influenced by some entity, activity, or agent.
///
/// Label: "influenced"
///
/// Description: "Capacity of an entity, activity, or agent to have an effect on the character, development, or behavior of another by means of usage, start, end, generation, invalidation, communication, derivation, attribution, association, or delegation."
pub const INFLUENCED: &str = "http://www.w3.org/ns/prov#influenced";

/// `prov:wasStartedBy` — An entity triggered the start of an activity.
///
/// Label: "wasStartedBy"
///
/// Description: "Start is when an activity is deemed to have been started by an entity, known as trigger."
pub const WAS_STARTED_BY: &str = "http://www.w3.org/ns/prov#wasStartedBy";

/// `prov:wasEndedBy` — An entity triggered the end of an activity.
///
/// Label: "wasEndedBy"
///
/// Description: "End is when an activity is deemed to have been ended by an entity, known as trigger."
pub const WAS_ENDED_BY: &str = "http://www.w3.org/ns/prov#wasEndedBy";

/// `prov:wasInvalidatedBy` — An entity was invalidated by an activity.
///
/// Label: "wasInvalidatedBy"
///
/// Description: "Invalidation is the start of the destruction, cessation, or expiry of an existing entity by an activity."
pub const WAS_INVALIDATED_BY: &str = "http://www.w3.org/ns/prov#wasInvalidatedBy";

/// `prov:hadUsage` — A usage that is the cause of a derivation.
///
/// Label: "hadUsage"
///
/// Description: "The prov:hadUsage property had a prov:Usage."
pub const HAD_USAGE: &str = "http://www.w3.org/ns/prov#hadUsage";

/// `prov:hadGeneration` — The generation that is the cause of a derivation.
///
/// Label: "hadGeneration"
///
/// Description: "The prov:hadGeneration property had a prov:Generation."
pub const HAD_GENERATION: &str = "http://www.w3.org/ns/prov#hadGeneration";

/// `prov:wasMemberOf` — An entity is or was a member of a collection.
///
/// Label: "wasMemberOf"
///
/// Description: "An entity was a member of this collection at some point in time."
pub const WAS_MEMBER_OF: &str = "http://www.w3.org/ns/prov#wasMemberOf";
